# Generated by Django 5.2.17 on 2026-09-03 19:58

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("vegetarian", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("available_until", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                ("requests", models.TextField(blank=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=7)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pizzeria.pizza"
                    ),
                ),
            ],
        ),
    ]
